import { Router } from "express";
import accountsRouter from "./accounts.js";
import contactsRouter from "./contacts.js";
import leadsRouter from "./leads.js";
import opportunitiesRouter from "./opportunities.js";
import quotesRouter from "./quotes.js";
import searchRouter from "./search.js";
import dashboardRouter from "./dashboard.js";
import productsRouter from "./products.js";
import pricebooksRouter from "./pricebooks.js";
import pricebookEntriesRouter from "./pricebookEntries.js";
import opportunityLineItemsRouter from "./opportunityLineItems.js";
import opportunityContactRolesRouter from "./opportunityContactRoles.js";
import quoteLineItemsRouter from "./quoteLineItems.js";
import tasksRouter from "./tasks.js";
import eventsRouter from "./events.js";
import ordersRouter from "./orders.js";
import orderItemsRouter from "./orderItems.js";
import contractsRouter from "./contracts.js";
import contractLineItemsRouter from "./contractLineItems.js";
import poolConsumptionsRouter from "./poolConsumptions.js";
import invoicesRouter from "./invoices.js";
import invoiceLineItemsRouter from "./invoiceLineItems.js";
import rolesRouter from "./roles.js";
import permissionProfilesRouter from "./permissionProfiles.js";
import permissionSetsRouter from "./permissionSets.js";
import orgWideDefaultsRouter from "./orgWideDefaults.js";
import sharingRulesRouter from "./sharingRules.js";
import workflowRulesRouter from "./workflowRules.js";
import approvalProcessesRouter from "./approvalProcesses.js";
import territoriesRouter from "./territories.js";
import territoryModelsRouter from "./territoryModels.js";
import territoryTypesRouter from "./territoryTypes.js";
import reportsRouter from "./reports.js";
import queryRouter from "./query.js";
import campaignsRouter from "./campaigns.js";
import validationRulesRouter from "./validationRules.js";
import fieldHistoryRouter from "./fieldHistory.js";
import usersRouter from "./users.js";
import approvalsRouter from "./approvals.js";
import forecastPeriodsRouter from "./forecastPeriods.js";
import forecastsRouter from "./forecasts.js";
import quotasRouter from "./quotas.js";

const router = Router();

router.use("/accounts", accountsRouter);
router.use("/contacts", contactsRouter);
router.use("/leads", leadsRouter);
router.use("/opportunities", opportunitiesRouter);
router.use("/quotes", quotesRouter);
router.use("/search", searchRouter);
router.use("/dashboard", dashboardRouter);
router.use("/products", productsRouter);
router.use("/pricebooks", pricebooksRouter);
router.use("/pricebook-entries", pricebookEntriesRouter);
router.use("/tasks", tasksRouter);
router.use("/events", eventsRouter);
router.use(opportunityLineItemsRouter);
router.use(opportunityContactRolesRouter);
router.use(quoteLineItemsRouter);
router.use("/orders", ordersRouter);
router.use("/order-items", orderItemsRouter);
router.use("/contracts", contractsRouter);
router.use("/contract-line-items", contractLineItemsRouter);
router.use("/pool-consumptions", poolConsumptionsRouter);
router.use("/invoices", invoicesRouter);
router.use("/invoice-line-items", invoiceLineItemsRouter);
router.use(rolesRouter);
router.use(permissionProfilesRouter);
router.use(permissionSetsRouter);
router.use(orgWideDefaultsRouter);
router.use(sharingRulesRouter);
router.use("/workflows", workflowRulesRouter);
router.use("/approval-processes", approvalProcessesRouter);
router.use("/territories", territoriesRouter);
router.use("/territory-models", territoryModelsRouter);
router.use("/territory-types", territoryTypesRouter);
router.use("/reports", reportsRouter);
router.use("/query", queryRouter);
router.use("/campaigns", campaignsRouter);
router.use("/validation-rules", validationRulesRouter);
router.use("/field-history", fieldHistoryRouter);
router.use("/users", usersRouter);
router.use("/approvals", approvalsRouter);
router.use("/forecast-periods", forecastPeriodsRouter);
router.use("/forecasts", forecastsRouter);
router.use("/quotas", quotasRouter);

// Health check
router.get("/health", (_req, res) => {
  res.json({ status: "ok", timestamp: new Date().toISOString() });
});

export default router;
